### PR TITLE
Changes to allow for multiple Rmd files

### PR DESCRIPTION
**Pull request by ilsePit**
Line 5: Edited description parameter rmd_file to more clearly state to enter multiple Rmd files as a list.
Line 38: Added [i] to forloop over rmd_file so it allows for multiple Rmd files in the parameter rmd_file.

### CODE REVIEW

**Comment by crsh** [comment]
This is great, @ilsePit, thank you. Does this work if multiple Rmd files are as `c("file1.Rmd", "file2.Rmd")` and `list("file1.Rmd", "file2.Rmd")`? If the latter does not work, it may make sense to slightly change the wording in the documentation to "One path or a vector of paths"?

**Comment by crsh** [comment]
Oh, and if you like, feel free to add yourself as a contributor to `DESCRIPTION`.

**Comment by ilsePit** [comment]
You're right, good point! it indeed only works with c("file1.Rmd", "file2.Rmd"). I will make the edit to the documentation.

**Comment by crsh** [comment]
Great, thanks!

**Pull request merged**
